package ke.don.domain

data class ProjectItem(
    val id: String,
    val title: String,
    val category: String,
    val dataSizeMb: Double,
    val status: String
)

val sampleProjectItems = listOf(
    ProjectItem("1", "Jetpack Compose Design System", "UI Framework", 120.5, "Active"),
    ProjectItem("2", "Offline Cache Sync (Room DB)", "Storage", 45.0, "Active"),
    ProjectItem("3", "Hilt Dependency Refactor", "Architecture", 88.2, "Idle"),
    ProjectItem("4", "LeakCanary Performance Fixes", "Optimization", 15.0, "Active"),
    ProjectItem("5", "Biometric Auth Integration", "Security", 30.5, "Completed"),
    ProjectItem("6", "Multi-Module Navigation Config", "Architecture", 24.1, "Active"),
    ProjectItem("7", "Background WorkManager Setup", "Sync", 65.4, "Idle"),
    ProjectItem("8", "Proto DataStore Migration", "Storage", 12.8, "Completed"),
    ProjectItem("9", "Firebase Crashlytics Event Logging", "Analytics", 8.5, "Active"),
    ProjectItem("10", "Custom Canvas Charts Engine", "UI Framework", 145.2, "Active"),
    ProjectItem("11", "CI/CD GitHub Actions Pipeline", "DevOps", 200.0, "Completed"),
    ProjectItem("12", "App Startup Time Optimization", "Optimization", 34.0, "Active"),
    ProjectItem("13", "Dynamic Material You Theming", "UI Framework", 18.2, "Active"),
    ProjectItem("14", "Encrypted SharedPreferences Sync", "Security", 22.1, "Idle"),
    ProjectItem("15", "Ktor Network Resilience Policies", "Network", 75.0, "Active"),
    ProjectItem("16", "Sentry Performance Tracing Integration", "Analytics", 41.5, "Active"),
    ProjectItem("17", "Baseline Profiles Generation", "Optimization", 110.0, "Completed"),
    ProjectItem("18", "Bluetooth LE Peripheral Scanner", "Hardware", 92.4, "Active"),
    ProjectItem("19", "Automated UI Screenshot Tests", "Testing", 160.0, "Idle"),
    ProjectItem("20", "Deep Link Intent Filter Mapping", "Navigation", 14.3, "Active"),
    ProjectItem("21", "Push Notifications Segmenting", "Marketing", 28.0, "Completed"),
    ProjectItem("22", "R8 Shrinkage Rule Tuning", "Optimization", 55.5, "Active"),
    ProjectItem("23", "Paging 3 Infinite Remote Mediator", "Storage", 130.4, "Active"),
    ProjectItem("24", "CameraX Video Capture Workflow", "Hardware", 175.0, "Idle"),
    ProjectItem("25", "Biometric Prompt Fallback Layouts", "Security", 11.2, "Completed"),
    ProjectItem("26", "Lottie Vector Animations Cache", "UI Framework", 84.6, "Active"),
    ProjectItem("27", "SQLDelight Multiplatform Schema", "Storage", 95.0, "Active"),
    ProjectItem("28", "Mock Web Server Integration Tests", "Testing", 118.0, "Completed"),
    ProjectItem("29", "Memory Leak Audit (Heap Dumps)", "Optimization", 50.0, "Active"),
    ProjectItem("30", "Glance App Widget Engine", "UI Framework", 37.4, "Idle"),
    ProjectItem("31", "ExoPlayer Adaptive Stream Caching", "Media", 210.5, "Active"),
    ProjectItem("32", "In-App Update Workflow Handler", "Core", 19.8, "Completed"),
    ProjectItem("33", "WebView Javascript Bridge Client", "Core", 29.5, "Active"),
    ProjectItem("34", "Health Connect Step Counter Sync", "Hardware", 66.0, "Active"),
    ProjectItem("35", "Coroutines SupervisorScope Setup", "Architecture", 15.6, "Completed"),
    ProjectItem("36", "Telemetry Payload Compression", "Network", 48.2, "Idle"),
    ProjectItem("37", "Data Matrix Barcode Scanner", "Hardware", 83.1, "Active"),
    ProjectItem("38", "Choreographer Frame Render Metrics", "Optimization", 125.0, "Active"),
    ProjectItem("39", "Vector Asset Path Optimizations", "UI Framework", 22.0, "Completed"),
    ProjectItem("40", "User Session Expiry Watchdog", "Security", 17.5, "Active"),
    ProjectItem("41", "Play Integrity Token Attestation", "Security", 73.4, "Idle"),
    ProjectItem("42", "Localization Translation Bundles", "Core", 31.0, "Completed"),
    ProjectItem("43", "Font Pre-loading & Subset Layouts", "UI Framework", 40.5, "Active"),
    ProjectItem("44", "WebSockets Real-time Chat Feed", "Network", 115.0, "Active"),
    ProjectItem("45", "NFC Badge Verification Engine", "Hardware", 89.7, "Idle"),
    ProjectItem("46", "Room Multi-Instance Invalidation", "Storage", 102.3, "Active"),
    ProjectItem("47", "LeakCanary Automated Heap Dumps", "Optimization", 16.5, "Completed"),
    ProjectItem("48", "Compose UI Multipreview Annotations", "UI Framework", 25.0, "Active"),
    ProjectItem("49", "Network Capabilities Connection Wire", "Network", 12.0, "Active"),
    ProjectItem("50", "Offline Vector Map Tile Caching", "Storage", 310.2, "Idle")
)

